### PR TITLE
[STRATCONN-130] Add tvOS Support 

### PR DESCRIPTION
**Pull request by briemcnally**
JIRA: https://segment.atlassian.net/browse/STRATCONN-130

## Problem 
Fixes error customer's were receiving when trying to integrate with tvOS targets:
```
[!] The platform of the target `FOXNOW` (tvOS 11.0) is not compatible with `Segment-Adobe-Analytics (1.3.0)`, which does not support `tvOS`.
```
## Solution
In order to fix the error we need to specify the Adobe pod subspec for tvOS targets in our podspec. 

## Verification
Added a tvOS target to the Example App.
Successfully able to pod install from a tvOS target.

### CODE REVIEW

**Comment by gpsamson** [comment]
@briemcnally Were you able to add tvOS as a platform for unit tests?

**Comment by briemcnally** [comment]
@gpsamson I was under the impression we were skipping add unit tests for tvOS per the JIRA, as long as iOS unit tests were still passing and the tvOS was bundling.

**Comment by briemcnally** [comment]
I can work on adding unit tests to `Segment-Adobe-Analytics_TVOSTests` if we think that is is a blocker for merging.

**Comment by gpsamson** [comment]
> I can work on adding unit tests to Segment-Adobe-Analytics_TVOSTests if we think that is is a blocker for merging.

That's OK. We can go without implementing tvOS platforms to our unit tests as long as we can import the pod into our project.

**Pull request merged**
